### ISSUE TITLE
No module named Cython.Distutils during install

### ISSUE THREAD

**Issue by prescottprue** [marionleborgne/cloudbrain#46]
```
Writing /tmp/easy_install-UVNqjE/pyliblo-0.10.0/setup.cfg
Running pyliblo-0.10.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-UVNqjE/pyliblo-0.10.0/egg-dist-tmp-MlAFc9
Traceback (most recent call last):
  File "setup.py", line 20, in <module>
    long_description=read("README.md"))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 152, in setup
    dist.run_commands()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "build/bdist.macosx-10.10-intel/egg/setuptools/command/install.py", line 67, in run
  File "build/bdist.macosx-10.10-intel/egg/setuptools/command/install.py", line 117, in do_egg_install
  File "build/bdist.macosx-10.10-intel/egg/setuptools/command/easy_install.py", line 380, in run
  File "build/bdist.macosx-10.10-intel/egg/setuptools/command/easy_install.py", line 610, in easy_install
  File "build/bdist.macosx-10.10-intel/egg/setuptools/command/easy_install.py", line 661, in install_item
  File "build/bdist.macosx-10.10-intel/egg/setuptools/command/easy_install.py", line 709, in process_distribution
  File "build/bdist.macosx-10.10-intel/egg/pkg_resources/__init__.py", line 800, in resolve
  File "build/bdist.macosx-10.10-intel/egg/pkg_resources/__init__.py", line 1050, in best_match
  File "build/bdist.macosx-10.10-intel/egg/pkg_resources/__init__.py", line 1062, in obtain
  File "build/bdist.macosx-10.10-intel/egg/setuptools/command/easy_install.py", line 629, in easy_install
  File "build/bdist.macosx-10.10-intel/egg/setuptools/command/easy_install.py", line 659, in install_item
  File "build/bdist.macosx-10.10-intel/egg/setuptools/command/easy_install.py", line 844, in install_eggs
  File "build/bdist.macosx-10.10-intel/egg/setuptools/command/easy_install.py", line 1072, in build_and_install
  File "build/bdist.macosx-10.10-intel/egg/setuptools/command/easy_install.py", line 1058, in run_setup
  File "build/bdist.macosx-10.10-intel/egg/setuptools/sandbox.py", line 240, in run_setup
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "build/bdist.macosx-10.10-intel/egg/setuptools/sandbox.py", line 193, in setup_context
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "build/bdist.macosx-10.10-intel/egg/setuptools/sandbox.py", line 164, in save_modules
  File "build/bdist.macosx-10.10-intel/egg/setuptools/sandbox.py", line 139, in resume
  File "build/bdist.macosx-10.10-intel/egg/setuptools/sandbox.py", line 152, in save_modules
  File "build/bdist.macosx-10.10-intel/egg/setuptools/sandbox.py", line 193, in setup_context
  File "build/bdist.macosx-10.10-intel/egg/setuptools/sandbox.py", line 237, in run_setup
  File "build/bdist.macosx-10.10-intel/egg/setuptools/sandbox.py", line 267, in run
  File "build/bdist.macosx-10.10-intel/egg/setuptools/sandbox.py", line 236, in runner
  File "build/bdist.macosx-10.10-intel/egg/setuptools/sandbox.py", line 46, in _execfile
  File "/tmp/easy_install-UVNqjE/pyliblo-0.10.0/setup.py", line 20, in <module>
    long_description=read("README.md"))
ImportError: No module named Cython.Distutils
```

I got this error while trying to run `sudo python setup.py install` even after doing ` brew install liblo`. It seems to be a problem with my environment, and is most likely related to liblo not being installed correctly.

Any Ideas?

**Comment by marionleborgne** [comment]
@prescottprue do you have `python-dev` installed?

**Comment by marionleborgne** [comment]
@prescottprue ping? :)

**Comment by prescottprue** [comment]
I followed the install instructions and already had Python 2.7 installed. Is there a separate install command that I could have missed to install python-dev or is that included in the python version build?

**Comment by prescottprue** [comment]
I was able to fix this by running `pip install cython`. Maybe we should add that to the install script or to the list of things to do in the README.
